# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/aya/lab02

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/aya/lab02

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/aya/lab02/CMakeFiles /mnt/c/aya/lab02/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/aya/lab02/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lab_o_two

# Build rule for target.
lab_o_two: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab_o_two
.PHONY : lab_o_two

# fast build rule for target.
lab_o_two/fast:
	$(MAKE) -f CMakeFiles/lab_o_two.dir/build.make CMakeFiles/lab_o_two.dir/build
.PHONY : lab_o_two/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

sources/experiment.o: sources/experiment.cpp.o

.PHONY : sources/experiment.o

# target to build an object file
sources/experiment.cpp.o:
	$(MAKE) -f CMakeFiles/lab_o_two.dir/build.make CMakeFiles/lab_o_two.dir/sources/experiment.cpp.o
.PHONY : sources/experiment.cpp.o

sources/experiment.i: sources/experiment.cpp.i

.PHONY : sources/experiment.i

# target to preprocess a source file
sources/experiment.cpp.i:
	$(MAKE) -f CMakeFiles/lab_o_two.dir/build.make CMakeFiles/lab_o_two.dir/sources/experiment.cpp.i
.PHONY : sources/experiment.cpp.i

sources/experiment.s: sources/experiment.cpp.s

.PHONY : sources/experiment.s

# target to generate assembly for a file
sources/experiment.cpp.s:
	$(MAKE) -f CMakeFiles/lab_o_two.dir/build.make CMakeFiles/lab_o_two.dir/sources/experiment.cpp.s
.PHONY : sources/experiment.cpp.s

sources/source.o: sources/source.cpp.o

.PHONY : sources/source.o

# target to build an object file
sources/source.cpp.o:
	$(MAKE) -f CMakeFiles/lab_o_two.dir/build.make CMakeFiles/lab_o_two.dir/sources/source.cpp.o
.PHONY : sources/source.cpp.o

sources/source.i: sources/source.cpp.i

.PHONY : sources/source.i

# target to preprocess a source file
sources/source.cpp.i:
	$(MAKE) -f CMakeFiles/lab_o_two.dir/build.make CMakeFiles/lab_o_two.dir/sources/source.cpp.i
.PHONY : sources/source.cpp.i

sources/source.s: sources/source.cpp.s

.PHONY : sources/source.s

# target to generate assembly for a file
sources/source.cpp.s:
	$(MAKE) -f CMakeFiles/lab_o_two.dir/build.make CMakeFiles/lab_o_two.dir/sources/source.cpp.s
.PHONY : sources/source.cpp.s

tests/test.o: tests/test.cpp.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... lab_o_two"
	@echo "... tests"
	@echo "... sources/experiment.o"
	@echo "... sources/experiment.i"
	@echo "... sources/experiment.s"
	@echo "... sources/source.o"
	@echo "... sources/source.i"
	@echo "... sources/source.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

